export function createConfig(c: PartialSiteConfig): SiteConfig {
	const ret: SiteConfig = {
		author: {
			name: "Test",
			email: "test@example.com"
		}
		blog: {
			hostname: "example.com",
			title: "Aki-SSG",
			description: "Yet another site generated by Aki-SSG",
			favicon: "/favicon.ico",
		},
		style: {
			primary_color: "#6db0ec",
			header_image: {
				default: "https://blog-oss.allenyou.top/image/658ad4c208349.png",
				dark: "https://blog-oss.allenyou.top/image/658ad4c208349.png",
			},
		},
		comment: {
			enabled: false,
		},
		gravatar_mirror: "https://gravatar.com/avatar/",
	};
	if (c.gravatar_mirror !== undefined) {
		ret.gravatar_mirror = c.gravatar_mirror;
	}
	if (c.comment !== undefined) {
		ret.comment = c.comment;
	}
	if (c.blog !== undefined) {
		if (c.blog.hostname !== undefined) {
			ret.blog.hostname = c.blog.hostname;
		}
		if (c.blog.description !== undefined) {
			ret.blog.description = c.blog.description;
		}
		if (c.blog.title !== undefined) {
			ret.blog.title = c.blog.title;
		}
		if (c.blog.favicon !== undefined) {
			ret.blog.favicon = c.blog.favicon;
		}
	}
	if (c.author !== undefined) {
		if (c.author.name !== undefined) {
			ret.author.name = c.author.name;
		}
		if (c.author.email !== undefined) {
			ret.author.email = c.author.email;
		}
	}
	if (c.follow !== undefined) {
		ret.follow = c.follow;
	}
	if (c.style !== undefined) {
		if (c.style.primary_color !== undefined) {
			ret.style.primary_color = c.style.primary_color;
		}
		if (c.style.header_image !== undefined) {
			if (typeof c.style.header_image === "string") {
				ret.style.header_image.default = c.style.header_image;
				ret.style.header_image.dark = c.style.header_image;
			} else {
				ret.style.header_image = c.style.header_image;
			}
		}
	}
	return ret;
}
