import { createConfig } from "../utils/createConfig";

export const config: SiteConfig = createConfig({
		author: {
			name: "Test", // 作者名，在页脚、版权信息展示。
			email: "test@example.com", // 作者邮箱，用于获取在导航栏展示的头像。
		},
		blog: {
			hostname: "aki-ssg-kemiao.vercel.app", // 网站域名
			title: "Aki-SSG", // 网站标题
			description: "Yet another site generated by Aki-SSG", // 网站描述，在 Header 展示
			favicon: "/favicon.ico", // 网站 Favicon
			begin_year: 2024, // 网站起始年份，在 Footer 展示
		},
		style: {
			primary_color: "#6db0ec", // 网站主题色
//			header_image: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // 网站 Header 图像
			header_image: { // 也可以用这种方法为深色模式和浅色模式分别配置不同的图像
				default: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // 浅色模式
				dark: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // 深色模式
			},
		},
		comment: { // 评论配置
			enabled: "false", // 禁用评论功能
		},
		comment: { // 如下设置启用 Waline 评论
			enabled: "waline",
			waline_api: ""
		},
		optimize: { // 优化配置
			gravatar_mirror: "https://gravatar.com/avatar/", // Gravatar 镜像源
			cdn_prefix: "", // 可选，加载静态资源时使用的 CDN 地址前缀（参见 next.config.ts 文件中的 assetPrefix 配置项）
							// 如果该项没有配置，静态资源将全部从本地加载。
			thumb_query: "", // 可选，代表文章中引用图片的缩略图 URL 末尾的部分。
							// 当文章中图片没有完全加载时，将显示缩略图代替。
							// 如果该项没有配置，将不显示缩略图。
		},
		external_link: [ // 向导航栏添加的外部链接
			{
				title: "Example", // 链接标题
				url: "https://example.com" // 链接 URL
			}
		]
	});