import { createConfig } from "../utils/createConfig";

export const config: SiteConfig = createConfig({
		author: {
			name: "Test", // Author name, displayed on the footer and copyright.
			email: "test@example.com", // Author email, used to get the gravatar displayed on the navigation bar.
		},
		blog: {
			hostname: "aki-ssg-kemiao.vercel.app", // The domain of site.
			title: "喵落阁", // The title of site.
			description: "Yet another site generated by Aki-SSG", // The description of site, displayed on the header of site.
			favicon: "/favicon.ico", // The site Favicon.
			begin_year: 2024, // The beginning year of site, displayed on the footer of the site.
		},
		style: {
			primary_color: "#6db0ec", // The primary color of site.
			header_image: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // The header image of site.
			header_image: { // Or you can use this to set different images for light or dark mode.
				default: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // Light mode
				dark: "https://blog-oss.allenyou.top/image/658ad4c208349.png", // Dark mode
			},
		},
		comment: { // Comment configuration.
			enabled: "disable", // Disable comment.
		},
		comment: { // Or set it to enable waline comment.
			enabled: "waline",
			waline_api: ""
		},
		optimize: { // Some optimization configuration.
			gravatar_mirror: "https://gravatar.com/avatar/", // Gravatar mirror to use.
			cdn_prefix: "", // Optional, the cdn url prefix of your static assets. (Refers to assetPrefix config in next.config.ts)
							// If not set, static assets will be imported locally.
			thumb_query: "", // Optional, the part appended to the thumb image url refered in the posts and pages.
							// When the image is not fully loaded, the low resolution thumbnails will be displayed.
							// If not set, none of thumb will be displayed.
		},
		external_link: [ // External links added to navigation bar
			{
				title: "Example", // Title of external link
				url: "https://example.com" // URL of external link
			}
		]
	};);